@startuml
package "markdown-cli" {
  [parse]
}

package "markdown-common" {
  [Markdown String] <-up-> [CommonMark DOM]
  [CommonMark DOM] -right-> [Plain Text String] 
}

note left of [CommonMark DOM]
  https://models.accordproject.org/commonmark/markdown.html
end note

note right of [Markdown String]
  Markdown formatted text uses the 
  well-defined commonmark.org parser 
  and syntax
end note

package "markdown-cicero" {
  [CommonMark DOM] <-up-> [CiceroMark DOM]
}

note left of [CiceroMark DOM]
  https://models.accordproject.org/ciceromark/ciceromark.html
end note

package "markdown-html" {
  [CiceroMark DOM] <-up-> [HTML String]
}

@enduml