name: Build and Deploy Dingus

on:
  push:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Build Dingus
        run: |
            cd packages/dingus
            mkdir demo
            scripts/demodata.js > lib/sample.json
            node_modules/.bin/pug lib/index.pug --pretty --obj lib/sample.json --out demo
            node_modules/.bin/stylus -u autoprefixer-stylus < lib/index.styl > demo/index.css
            cp lib/templatemark.css demo/templatemark.css
            rm -rf lib/sample.json
            node_modules/.bin/browserify lib/index.js > demo/index.js

      - name: Set S3 
        run: |
            echo "AWS_S3_BUCKET=${{secrets.AWS_S3_BUCKET}}" >> $GITHUB_ENV

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'packages/dingus/demo'

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}